### ISSUE TITLE
Afte installin the 1.23 firmware Gree application could not connect the HVAc

### ISSUE THREAD

**Issue by Tuokki1** [aivus/com.gree#157] opened 2024-09-18 18:26 UTC
After installing the 1.23 firmware  (reinstalling does not help). The application finds the device (IP) and installing goes to the end OK. However after installation, Homey could not connect the air conditioner.

Any suggestions?

5c25740a-a644-4014-82fc-bda74da2a79f

Br, 

Tuomas

**Comment by aivus** [comment] 2024-09-18 18:30
Hello @Tuokki1 

I'm closing it as a duplicate of https://github.com/aivus/com.gree/issues/85.

**Closed by aivus** 2024-09-18 18:30 UTC
