### ISSUE TITLE
Your HVAC went Offline

### ISSUE THREAD

**Issue by oliviervb** [aivus/com.gree#22] opened 2019-08-06 12:44 UTC
everything goes well during installation. aftherwards the device 
leave a warning triangle with the message: Your HVAC went offline. trying to reconnect.

**Comment by aivus** [comment] 2019-08-07 07:14
Hi @oliviervb 

This message appears when App can not get response from the HVAC during timeout.

Is this message showing continuously? Does your HVAC WiFi module still on?

**Comment by oliviervb** [comment] 2019-08-07 11:03
@aivus thank you for your reply, however 
The message is constantly. I think there is nothing wrong with the wifi, because it's working  perfectly with the gree smartphone app.

**Comment by aivus** [comment] 2019-08-07 13:21
I'll prepare version with additional logging and will ask you to update to this version.

**Comment by aivus** [comment] 2019-08-08 06:42
@oliviervb I got your diagnostic report, but didn't found any issues there.

Could you please share your email address which you are using in homey?
I will push test version for you via Homey Apps with additional logging.

Thanks.

**Comment by aivus** [comment] 2019-08-08 06:42
My email: ilya@antipenko.pp.ua

**Comment by aivus** [comment] 2019-08-08 13:33
According to logs HVAC doesn't respond to any requests except scanning request.

I'll try to implement broadcast approach. Maybe it helps.
https://github.com/tomikaa87/gree-remote#remarks-1

@oliviervb could you please check and verify that your router doesn't have enabled any options like "client isolation" etc

**Comment by aivus** [comment] 2019-08-16 08:28
Hey @oliviervb 

Did you have a chance to check router settings?

**Comment by oliviervb** [comment] 2019-08-16 18:02
Hey @aivus,
I checked the router settings. I think everything's okay.
Could you try to connect? Or is there a special setting in Homey?

**Comment by thaserge** [comment] 2019-08-21 21:58
but I have 2 air conditioners installed (living room N1 and bedroom N2) c&h CH-S12FTXTB2S-W and everything works fine with N2, but the control is a bit slow, but when I add N1 both don’t work.  
If i add only N1 it does not work at all - writes an error - HAVC went offline...

Говорю по русски )

**Comment by aivus** [comment] 2019-08-22 10:46
@oliviervb 
App automatically tries to connect HVAC every few seconds.

I will try to implement broadcast messaging but it takes time.
That's why I asked you to check your router settings and verify that Homey and HVAC are in the same network

**Comment by oliviervb** [comment] 2019-08-22 14:52
yes they are in the same network

**Comment by aivus** [comment] 2019-09-01 19:41
Hey @oliviervb.

I've pushed new alpha 0.1.3 version. Could you please check it?

If it doesn't work for you please create new diagnostic report.

**Comment by thaserge** [comment] 2019-09-01 21:50
I tried to control AC from homkit, but they do not react to the command the first time, I still can not send a report. 

The message appears: Something went wrong, please try again. (The item could not be found).

AC is forwarded to homkit through the plugin from sprut

**Comment by aivus** [comment] 2019-09-02 07:57
@thaserge please create separate issue for this.

This one is about topic starter problem.

**Comment by aivus** [comment] 2019-09-02 08:02
@oliviervb according to your last report (ID 7faa7c81-5eb2-4981-b65f-ff1c0f6daa22) I see that Homey can see your AC, but it doesn't response to the Homey (or Homey can not get this responses).

**Comment by oliviervb** [comment] 2019-09-02 15:59
@aivus okay, and what can be the solution?

**Comment by aivus** [comment] 2019-10-17 21:44
@oliviervb I've published 0.1.4 version to the alpha channel with possible fix.

Please check it.

**Comment by oliviervb** [comment] 2019-10-17 21:51
Hello,
Same problem. Thx for not giving up!
Grts
Olivier

Op do 17 okt. 2019 23:44 schreef Ilya Antipenko <notifications@github.com>:

**Comment by jahnkenneth** [comment] 2020-07-12 20:19
I also have this problem... :-( 
Any news?

**Comment by aivus** [comment] 2022-07-17 20:05
Hey folks,

Do you still have this issue after the latest update?

**Comment by rentisob** [comment] 2023-02-07 09:34
Hi Aivus,
I'm facing again with the same issue that I mentioned to you some month ago. 
I have 2 Gree air conditioners one of them is working great, but the second one cannot be integrated to Homey, the app says: No new devices have been found. It was working fine parallel for months, but after a power outage it cannot be integrated again to Homey.
Both systems are using the same Wifi SSID, and integrated into the Ewpe Smart application. Via the application both are working fine. 
I have just created a diagnostic report: 813c0a84-60d5-4777-be63-55da4855ee89.
Do you know what can be the reason? Thanks for your help!
Best regards,
Csaba

**Comment by rentisob** [comment] 2023-02-07 11:20
Hi Aivus,
Yes it helped, I had to use the circuit breaker. Thank you!

**Comment by WueBumbum** [comment] 2023-11-30 06:08
Hello,

I have the same issue. Both at home and at work. We have a very stable Ubiquity Wifi setup at both places. Sometimes it helps to restart the Homey App. When the AC's are shown offline in Homey they are always controlable via the Gree App.

Is there a connection retry after the homey app recognized an offline ac? I have seen a pull request for a configurable timeout in the settings, but have not found it.

best regards
Andreas

**Comment by aivus** [comment] 2023-12-02 17:05
Hello @WueBumbum 

To control AC from Homey we are connecting to unit via local network, when for Gree App it's a AC unit connects to the Gree servers. So, there is a differece.

Yes, I have a plan to publish version with configurable timeouts to the [test](https://homey.app/de-de/app/com.gree/Gree/test) channel this year. So, it would be possible for users to increase timeout in device settings.

> Is there a connection retry after the homey app recognized an offline ac?

Yes, Gree Homey app [constantly](https://github.com/aivus/com.gree/blob/6e027bcddabc1e6c56a3c8891c15726c8d449e53/drivers/gree_cooper_hunter_hvac/device.js#L11-L12) updates the status of the AC unit (temperature, modes, etc). In case there are [not response](https://github.com/aivus/com.gree/blob/6e027bcddabc1e6c56a3c8891c15726c8d449e53/drivers/gree_cooper_hunter_hvac/device.js#L14-L15) from the AC app marks device as offline, but still continue to request status updates.

`went offline` message means that device is not responding to the requests. I've noticed several times that re-enabling wifi module on AC helps.

**Comment by dsaw703** [comment] 2024-05-20 09:10
> Hey @aivus, I checked the router settings. I think everything's okay. Could you try to connect? Or is there a special setting in Homey?

Has there been a resolution to this issue?

**Comment by aivus** [comment] 2024-06-24 19:47
Looks like this issue is directly caused by https://github.com/aivus/com.gree/issues/85

Could you please post a firmware versions of the ACs (you can find them in EWPE Smart app)?

**Comment by dsaw703** [comment] 2024-06-24 20:09
The firmware versions are V1.39 for the wired controller and V1.21 for the wifi units.

Thanks.
________________________________

**Comment by aivus** [comment] 2024-09-19 19:24
I'm closing this issue as a duplicate of #85. Please subscribe to updates there if you are interested.

**Closed by aivus** 2024-09-19 19:24 UTC
Labels: bug

**Comment by aivus** [comment] 2024-09-23 21:52
Hello there,

I just released a test version with the possible fix, please [follow this steps](https://community.homey.app/t/app-pro-gree-hvac-app/30801/153?u=aivus)
