### ISSUE TITLE
HomeyKit

### ISSUE THREAD

**Issue by jahnkenneth** [aivus/com.gree#44] opened 2020-06-02 11:37 UTC
Hello,
This app also works for Wilfa AC.
However it does not show up in my HomeKit setup. Is this possible to fix?
I am using the HomeyKit app.

**Comment by aivus** [comment] 2020-06-02 12:00
Hey @jahnkenneth 

Thanks. I've added it to the supported list.

Unfortunately I don't have Apple devices and cannot test HomeKit.
What exactly doesn't work?

**Comment by jahnkenneth** [comment] 2020-06-02 12:22
The HomeyKit-app doesn’t recognize it as a thermostat. 
Maybe @robertklep can advise? :-)

**Comment by robertklep** [comment] 2020-06-02 13:30
The problem is that Homeykit only accepts thermostat devices that have both `measure_temperature` and `target_temperature` (these are both required capabilities for Homekit), and the Gree driver only has the latter :(

**Comment by jahnkenneth** [comment] 2020-06-02 14:51
@aivus Is this something that you could implement?

**Comment by aivus** [comment] 2020-06-02 14:58
@jahnkenneth ACs are not providing current temperature.

I'll check what I can do here.

**Comment by jahnkenneth** [comment] 2020-06-02 15:10
My AC provides the current temperature in the EWPE app... I have also gotten it to work in HomeBridge, where it also provides the current temperature. Also my Daikin AC works with HomeyKit...

**Comment by aivus** [comment] 2020-06-02 20:50
> My AC provides the current temperature in the EWPE app

That's interesting. Are you sure that it shows *current* information, not *target*?

I'm using a 3rd party library for interaction with AC and it doesn't have any options to get current temp from such ACs.

**Comment by aivus** [comment] 2020-06-02 20:55
I'll check adding `measure_temperature` to the driver and use the same temperature as in `target_temperature`.

@jahnkenneth I'll ask you to test this version before release to confirm that it works. Ok?
Please share with me email address that you are using for homey (please use my email from the github profile). It allows me to push alpha version to you.

**Comment by jahnkenneth** [comment] 2020-06-02 21:24
> > My AC provides the current temperature in the EWPE app
> 
> That's interesting. Are you sure that it shows _current_ information, not _target_?
> 
> I'm using a 3rd party library for interaction with AC and it doesn't have any options to get current temp from such ACs.

Yes, I am very sure. :-)

**Comment by aivus** [comment] 2020-06-03 14:31
Based on the sources of [Homebridge app](https://github.com/ddenisyuk/homebridge-gree-heatercooler/blob/3b50bbe6b7899ee38c461d9fdf6454ba1c0221fb/app/commandEnums.js#L33-L36) parameter `TemSen` can be used as a measured temperature.

But my HVAC reports 65 °C always (I believe it doesn't temperature sensor).
Testing in progress

All possible information from EWPE:
https://github.com/tomikaa87/gree-remote/issues/7

**Comment by grunci** [comment] 2020-06-12 11:38
Hi @aivus ,
Just substract 40 from the reported TemSen, and you will see the actual temperature in celsius.
I am investigating further in the area.

**Comment by aivus** [comment] 2020-06-12 20:06
Hey @grunci.

It's already investigated and pushed to the Homey's test channel: https://homey.app/en-us/app/com.gree/Gree/test/

Changes: https://github.com/aivus/com.gree/pull/49 and https://github.com/inwaar/gree-hvac-client/pull/11

Will be released 🔜

**Closed** 2020-06-15 17:25 UTC
Labels: enhancement, question, wait for stable release

**Comment by aivus** [comment] 2020-06-15 17:52
Done in v0.4.0
